language: node_js
node_js:
- "8.11.3"
before_install:
- npm install

script:
- docker pull nginx
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_NAME" --password-stdin
- docker build -t ying98/godeye_frontend .
- docker push ying98/godeye_frontend:latest
- docker run -d --name=customer -p 8889:8889 ying98/godeye_frontend
- docker ps